use_frameworks!

platform :ios, '8.0'

target 'testPaget_Example' do
  pod 'testPaget', :path => '../'

  target 'testPaget_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
